### ISSUE TITLE
A small typo in the crates.io description

### ISSUE THREAD

**Issue by zeritonius** [aubreyrs/prettylog-rs#1]
In the crates.io description, https://crates.io/crates/prettylog-rs

the link to your repository is https://github.com/aubreydll/prettylog-rs
(which gives a 404 error "not found" by GitHub)

instead of this one: 
https://github.com/aubreyrs/prettylog-rs

![typo](https://github.com/user-attachments/assets/d6224953-0263-48bd-8759-f07632b3bb47)

**Comment by aubreyrs** [comment]
Fixed, thank you! :)
